/**
 * 一次性迁移脚本：把 src/content/blogs/*.md 的 frontmatter 生成为静态
 * TS 模块（src/data/blogs-static.ts），供 SSR 页面直接 import。
 *
 * 动机：任何 SSR 页面只要 import astro:content，Astro 的内容运行时就会
 * 连同「整个数据层存储」（含全部文章正文，当前 ~125MB）一起打进服务端
 * bundle，撞 Worker 64MiB 上限。博客元数据改为纯静态模块后，
 * SSR 彻底不碰内容层；文章数据按架构由 D1 提供。
 *
 * 用法：npx tsx scripts/generate-blogs-static.ts
 * 重新生成前先增改 src/content/blogs/*.md 再跑本脚本。
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'src', 'content', 'blogs');
const outFile = path.join(root, 'src', 'data', 'blogs-static.ts');

const entries = readdirSync(dir)
  .filter((file) => file.endsWith('.md'))
  .sort()
  .map((file) => {
    const raw = readFileSync(path.join(dir, file), 'utf8');
    const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(raw);
    if (!match) throw new Error(`no frontmatter in ${file}`);
    const fm = YAML.parse(match[1]!) as Record<string, unknown>;
    if (typeof fm.name !== 'string' || typeof fm.type !== 'string') {
      throw new Error(`${file}: frontmatter must contain name and type`);
    }
    // 键统一转 camelCase：页面/组件全部按 camelCase 解构（blogUrl、logoScale…），
    // frontmatter 里的 snake_case 若原样透传会变成运行时静默取空。
    const data: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(fm)) {
      data[key.replace(/_([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())] = value;
    }
    return { id: file.replace(/\.md$/, ''), data };
  });

if (entries.length === 0) throw new Error('no blog entries found');

const body = [
  '// Auto-generated by scripts/generate-blogs-static.ts —— 请勿手改。',
  '// 数据来源：src/content/blogs/*.md（从 content collection 迁出：',
  '// SSR 一旦引入 astro:content 就会把整个数据层存储打进 bundle）。',
  '// 增改博客：编辑对应 .md 后重跑 npx tsx scripts/generate-blogs-static.ts',
  '/** 博客元数据（frontmatter 全量字段，键已转 camelCase）。 */',
  'export interface StaticBlogData {',
  '  name: string;',
  "  type: 'company' | 'personal';",
  '  author?: string;',
  '  description?: string;',
  '  domain?: string;',
  '  homepageUrl?: string;',
  '  blogUrl?: string;',
  '  rssUrl?: string;',
  '  sitemapUrl?: string;',
  '  logo?: string;',
  '  avatar?: string;',
  '  logoScale?: number;',
  '  categories?: string[];',
  '  demo?: boolean;',
  '}',
  '',
  'export interface StaticBlogEntry {',
  '  id: string;',
  '  data: StaticBlogData;',
  '}',
  '',
  `export const staticBlogs: StaticBlogEntry[] = ${JSON.stringify(entries, null, 2)};`,
  '',
].join('\n');

writeFileSync(outFile, body);
console.log(`✓ ${entries.length} blog(s) -> ${path.relative(root, outFile)}`);
