/// <reference types="astro/client" />

// Cloudflare bindings (DB, UPDATE_WORKFLOW, ASSETS) are typed by
// worker-configuration.d.ts (generated by `wrangler types`).
// Access via: import { env } from 'cloudflare:workers'
