// Auto-generated by scripts/generate-blogs-static.ts —— 请勿手改。
// 数据来源：src/content/blogs/*.md（从 content collection 迁出：
// SSR 一旦引入 astro:content 就会把整个数据层存储打进 bundle）。
// 增改博客：编辑对应 .md 后重跑 npx tsx scripts/generate-blogs-static.ts
/** 博客元数据（frontmatter 全量字段，键已转 camelCase）。 */
export interface StaticBlogData {
  name: string;
  type: 'company' | 'personal';
  author?: string;
  description?: string;
  domain?: string;
  homepageUrl?: string;
  blogUrl?: string;
  rssUrl?: string;
  sitemapUrl?: string;
  logo?: string;
  avatar?: string;
  logoScale?: number;
  categories?: string[];
  demo?: boolean;
}

export interface StaticBlogEntry {
  id: string;
  data: StaticBlogData;
}

export const staticBlogs: StaticBlogEntry[] = [
  {
    "id": "andrej-karpathy",
    "data": {
      "name": "Andrej Karpathy",
      "type": "personal",
      "author": "Andrej Karpathy",
      "description": "LLM 教育、AI 思考与工程实践。",
      "homepageUrl": "https://karpathy.ai/",
      "blogUrl": "https://karpathy.bearblog.dev/",
      "domain": "karpathy.bearblog.dev",
      "rssUrl": "https://karpathy.bearblog.dev/feed/",
      "avatar": "https://github.com/karpathy.png",
      "categories": [
        "AI",
        "Personal Growth"
      ],
      "demo": true
    }
  },
  {
    "id": "anthropic",
    "data": {
      "name": "Anthropic",
      "type": "company",
      "description": "AI 安全、研究与可靠智能体工程。",
      "homepageUrl": "https://www.anthropic.com/",
      "blogUrl": "https://www.anthropic.com/research",
      "domain": "anthropic.com",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/anthropic.svg",
      "sitemapUrl": "https://www.anthropic.com/sitemap.xml",
      "categories": [
        "AI",
        "Agent",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "cursor",
    "data": {
      "name": "Cursor",
      "type": "company",
      "author": "Cursor Team",
      "description": "编程智能体、模型训练与 Agent Harness 的官方工程博客。",
      "homepageUrl": "https://cursor.com/",
      "blogUrl": "https://cursor.com/blog",
      "domain": "cursor.com",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/cursor.svg",
      "logoScale": 0.9,
      "sitemapUrl": "https://cursor.com/sitemap.xml",
      "categories": [
        "Agent",
        "AI Coding / Developer Tools"
      ],
      "demo": true
    }
  },
  {
    "id": "dan-koe",
    "data": {
      "name": "Dan Koe",
      "type": "personal",
      "author": "Dan Koe",
      "description": "个人成长、AI 时代技能、策略思维与创作经济。",
      "homepageUrl": "https://thedankoe.com/",
      "blogUrl": "https://letters.thedankoe.com/",
      "domain": "letters.thedankoe.com",
      "avatar": "https://substackcdn.com/image/fetch/$s_!KH3R!,w_88,h_88,c_fill,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7591b09e-6d83-4960-a71c-e2060766c42a_728x728.jpeg",
      "rssUrl": "https://letters.thedankoe.com/feed",
      "sitemapUrl": "https://letters.thedankoe.com/sitemap.xml",
      "categories": [
        "Personal Growth",
        "AI"
      ],
      "demo": true
    }
  },
  {
    "id": "eleuther-ai",
    "data": {
      "name": "EleutherAI",
      "type": "company",
      "author": "EleutherAI",
      "description": "开源 LLM、可解释性与安全研究博客。",
      "homepageUrl": "https://www.eleuther.ai/",
      "blogUrl": "https://blog.eleuther.ai/",
      "domain": "blog.eleuther.ai",
      "logo": "https://blog.eleuther.ai/images/libre.svg",
      "rssUrl": "https://blog.eleuther.ai/index.xml",
      "sitemapUrl": "https://blog.eleuther.ai/sitemap.xml",
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "github-engineering",
    "data": {
      "name": "GitHub Engineering",
      "type": "company",
      "author": "GitHub Engineering",
      "description": "GitHub 工程团队博客，覆盖开发者平台、架构优化与 Copilot 工程。",
      "homepageUrl": "https://github.blog/",
      "blogUrl": "https://github.blog/engineering/",
      "domain": "github.blog",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/github.svg",
      "logoScale": 0.9,
      "rssUrl": "https://github.blog/engineering/feed/",
      "categories": [
        "Engineering / Infrastructure",
        "AI Coding / Developer Tools"
      ],
      "demo": true
    }
  },
  {
    "id": "google-deepmind",
    "data": {
      "name": "Google DeepMind",
      "type": "company",
      "author": "Google DeepMind",
      "description": "前沿模型、AI Safety 与科学研究官方博客。",
      "homepageUrl": "https://deepmind.google/",
      "blogUrl": "https://deepmind.google/blog/",
      "domain": "deepmind.google",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/deepmind-color.svg",
      "logoScale": 0.84,
      "rssUrl": "https://deepmind.google/blog/rss.xml",
      "sitemapUrl": "https://deepmind.google/sitemap.xml",
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "google-security",
    "data": {
      "name": "Google Security",
      "type": "company",
      "author": "Google Security",
      "description": "Google 官方安全博客，覆盖威胁情报、平台安全与企业安全。",
      "homepageUrl": "https://blog.google/",
      "blogUrl": "https://blog.google/security/",
      "domain": "blog.google",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/google-color.svg",
      "logoScale": 0.9,
      "rssUrl": "https://blog.google/security/rss/",
      "categories": [
        "Engineering / Infrastructure"
      ],
      "demo": true
    }
  },
  {
    "id": "hamel-husain",
    "data": {
      "name": "Hamel Husain",
      "type": "personal",
      "author": "Hamel Husain",
      "description": "Agent、Evals 与 AI 产品实践。",
      "homepageUrl": "https://hamel.dev/",
      "blogUrl": "https://hamel.dev/blog/",
      "avatar": "https://github.com/hamelsmu.png",
      "domain": "hamel.dev",
      "rssUrl": "https://hamel.dev/index.xml",
      "categories": [
        "Agent",
        "AI Coding / Developer Tools"
      ],
      "demo": true
    }
  },
  {
    "id": "jay-alammar",
    "data": {
      "name": "Jay Alammar",
      "type": "personal",
      "author": "Jay Alammar",
      "description": "LLM 可视化教育与深度解读。",
      "homepageUrl": "https://jalammar.github.io/",
      "blogUrl": "https://newsletter.languagemodels.co/",
      "domain": "newsletter.languagemodels.co",
      "rssUrl": "https://newsletter.languagemodels.co/feed",
      "avatar": "https://github.com/jalammar.png",
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "langchain",
    "data": {
      "name": "LangChain",
      "type": "company",
      "author": "LangChain",
      "description": "Agent 框架、Evals 与可观测性的官方博客。",
      "homepageUrl": "https://www.langchain.com/",
      "blogUrl": "https://www.langchain.com/blog",
      "domain": "langchain.com",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/langchain-color.svg",
      "logoScale": 0.94,
      "rssUrl": "https://www.langchain.com/blog/rss.xml",
      "sitemapUrl": "https://www.langchain.com/sitemap.xml",
      "categories": [
        "Agent",
        "AI Coding / Developer Tools"
      ],
      "demo": true
    }
  },
  {
    "id": "lastwhisper",
    "data": {
      "name": "LastWhisper",
      "type": "personal",
      "author": "LastWhisper",
      "description": "中文原创博客，分享关于 AI Agent / Context Engineering / AI Coding 的深度思考与实践。",
      "homepageUrl": "https://keli-wen.github.io/One-Poem-Suffices/",
      "blogUrl": "https://keli-wen.github.io/One-Poem-Suffices/",
      "domain": "keli-wen.github.io",
      "avatar": "https://github.com/keli-wen.png",
      "sitemapUrl": "https://keli-wen.github.io/One-Poem-Suffices/sitemap.xml",
      "categories": [
        "AI",
        "Agent",
        "AI Coding / Developer Tools"
      ],
      "demo": true
    }
  },
  {
    "id": "lilian-weng",
    "data": {
      "name": "Lil'Log",
      "type": "personal",
      "author": "Lilian Weng",
      "description": "深入梳理机器学习、LLM 与智能体研究。",
      "homepageUrl": "https://lilianweng.github.io/",
      "blogUrl": "https://lilianweng.github.io/",
      "domain": "lilianweng.github.io",
      "avatar": "https://github.com/lilianweng.png",
      "rssUrl": "https://lilianweng.github.io/index.xml",
      "sitemapUrl": "https://lilianweng.github.io/sitemap.xml",
      "categories": [
        "AI",
        "Agent",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "meta-ai",
    "data": {
      "name": "Meta AI",
      "type": "company",
      "author": "Meta AI",
      "description": "Meta 生成式 AI、Llama 与 AI 研究官方博客。",
      "homepageUrl": "https://ai.meta.com/",
      "blogUrl": "https://ai.meta.com/blog/",
      "domain": "ai.meta.com",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/metaai-color.svg",
      "logoScale": 0.9,
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "microsoft-research",
    "data": {
      "name": "Microsoft Research",
      "type": "company",
      "author": "Microsoft Research",
      "description": "LLM、Agent 与机器学习研究博客。",
      "homepageUrl": "https://www.microsoft.com/en-us/research/",
      "blogUrl": "https://www.microsoft.com/en-us/research/blog/",
      "domain": "microsoft.com",
      "logo": "https://cdn.jsdelivr.net/gh/gilbarbara/logos@main/logos/microsoft-icon.svg",
      "logoScale": 0.84,
      "rssUrl": "https://www.microsoft.com/en-us/research/feed/",
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "mistral-ai",
    "data": {
      "name": "Mistral AI",
      "type": "company",
      "author": "Mistral AI",
      "description": "开源模型与模型研究新闻。",
      "homepageUrl": "https://mistral.ai/",
      "blogUrl": "https://mistral.ai/news/",
      "domain": "mistral.ai",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/mistral-color.svg",
      "rssUrl": "https://mistral.ai/news/rss",
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "moonshot",
    "data": {
      "name": "Moonshot",
      "type": "company",
      "author": "Moonshot AI",
      "description": "Moonshot 的大模型、Agent 与评测技术官方博客。",
      "homepageUrl": "https://www.kimi.com/",
      "blogUrl": "https://www.kimi.com/en/blog/",
      "domain": "kimi.com",
      "logo": "/vendors/moonshotai.svg",
      "categories": [
        "AI",
        "Agent",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "openai",
    "data": {
      "name": "OpenAI",
      "type": "company",
      "description": "研究、产品与 AI 系统实践文章。",
      "homepageUrl": "https://openai.com/",
      "blogUrl": "https://openai.com/news/",
      "domain": "openai.com",
      "logo": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/openai.svg",
      "rssUrl": "https://openai.com/news/rss.xml",
      "sitemapUrl": "https://openai.com/sitemap.xml",
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "paul-graham",
    "data": {
      "name": "Paul Graham Essays",
      "type": "personal",
      "author": "Paul Graham",
      "description": "关于创造、创业、写作与长期工作的随笔。",
      "homepageUrl": "https://paulgraham.com/",
      "blogUrl": "https://paulgraham.com/articles.html",
      "domain": "paulgraham.com",
      "avatar": "https://s.turbifycdn.com/aah/paulgraham/headshot-11.gif",
      "categories": [
        "Personal Growth",
        "Internet / Technology"
      ],
      "demo": true
    }
  },
  {
    "id": "qwen",
    "data": {
      "name": "Qwen",
      "type": "company",
      "author": "Qwen Team",
      "description": "阿里通义千问模型团队的官方博客，覆盖 LLM、多模态与 Agent。",
      "homepageUrl": "https://qwenlm.github.io/",
      "blogUrl": "https://qwenlm.github.io/blog/",
      "domain": "qwenlm.github.io",
      "avatar": "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@1.94.0/icons/qwen-color.svg",
      "sitemapUrl": "https://qwenlm.github.io/en/sitemap.xml",
      "categories": [
        "AI",
        "Research",
        "Agent"
      ],
      "demo": true
    }
  },
  {
    "id": "sebastian-raschka",
    "data": {
      "name": "Ahead of AI",
      "type": "personal",
      "author": "Sebastian Raschka",
      "description": "LLM 训练、微调与研究的长文博客。",
      "homepageUrl": "https://sebastianraschka.com/",
      "blogUrl": "https://magazine.sebastianraschka.com/",
      "avatar": "https://github.com/rasbt.png",
      "domain": "magazine.sebastianraschka.com",
      "rssUrl": "https://magazine.sebastianraschka.com/feed",
      "sitemapUrl": "https://magazine.sebastianraschka.com/sitemap.xml",
      "categories": [
        "AI",
        "Research"
      ],
      "demo": true
    }
  },
  {
    "id": "z-ai",
    "data": {
      "name": "Z.ai",
      "type": "company",
      "author": "Z.ai",
      "description": "Z.ai 的 GLM 模型、Agent、长上下文与 AI Coding 技术文章。",
      "homepageUrl": "https://z.ai/",
      "blogUrl": "https://z.ai/",
      "domain": "z.ai",
      "logo": "/vendors/z-ai.svg",
      "logoScale": 0.9,
      "categories": [
        "AI",
        "Agent"
      ],
      "demo": true
    }
  }
];
